name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PR to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adoptopenjdk'  # You can use openjdk as well

      # Step 3: Cache dependencies (to speed up builds)
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository  # Cache Maven dependencies
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # Cache key
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the project using Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests=false  # Install and run tests

      # Step 5: Run unit tests
      - name: Run Tests with Maven
        run: mvn test  # Run the unit tests

      # Step 6: (Optional) Deploy to a server (e.g., AWS, or custom environment)
      # This step depends on your specific deployment setup.
      # You can use actions for deployment or scripts as needed.
