name: Java CI with Maven

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Set the operating system for the job
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adoptopenjdk'

      # Build with Maven
      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      # Run tests with Maven
      - name: Run tests with Maven
        run: mvn test --no-transfer-progress